-- ============================================================
-- 로컬 검증 전용 스키마. 운영 DB에 절대 적용하지 말 것.
-- 근거: docs/erd/kbfido-columns.txt (KBFIDO 39 테이블 / 354 컬럼)
-- 시퀀스 이름 <TABLE>_SEQ 는 임시. 실제 이름 확인 후 교체.
-- ============================================================
-- 안전장치: 오류 발생 시 즉시 중단(운영 DB 오적용 시 뒤 구문이 실행되지 않도록).
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
WHENEVER OSERROR EXIT FAILURE ROLLBACK

-- 대상 검증: 로컬 검증용 FREEPDB1 이 아니면 ORA-20999 로 중단한다.
DECLARE
  v_db VARCHAR2(128);
BEGIN
  SELECT SYS_CONTEXT('USERENV', 'DB_NAME') INTO v_db FROM DUAL;
  IF UPPER(v_db) != 'FREE' THEN
    RAISE_APPLICATION_ERROR(-20999,
      '중단: 로컬 검증 전용 스크립트다. 대상 DB_NAME=' || v_db || ' (기대값 FREE)');
  END IF;
END;
/

ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = KBFIDO;

CREATE TABLE APPID (
  IDX                          NUMBER(11,0) NOT NULL,
  COMPANY_IDX                  NUMBER,
  APPID                        VARCHAR2(128),
  MEMO                         VARCHAR2(512),
  STATUS                       VARCHAR2(12) DEFAULT 'use' NOT NULL,
  DEVICE                       VARCHAR2(128),
  DEVICE_DEFAULT               VARCHAR2(1) DEFAULT 'F' NOT NULL,
  SERVICENAME                  VARCHAR2(512),
  CREATEDTIME                  TIMESTAMP DEFAULT SYSDATE,
  UPDATEDTIME                  TIMESTAMP DEFAULT SYSDATE,
  CONSTRAINT APPID_PK PRIMARY KEY (IDX)
);

CREATE TABLE APPSERVER (
  IDX                          NUMBER NOT NULL,
  COMPANY_IDX                  NUMBER,
  MEMBER_CODE                  VARCHAR2(32) NOT NULL,
  MEMBER_ID                    VARCHAR2(32) NOT NULL,
  TYPE                         VARCHAR2(10) DEFAULT 'use' NOT NULL,
  NOTE                         VARCHAR2(128),
  CREATEDTIME                  TIMESTAMP DEFAULT sysdate NOT NULL,
  UPDATEDTIME                  TIMESTAMP DEFAULT sysdate NOT NULL,
  CONSTRAINT APPSERVER_PK PRIMARY KEY (IDX)
);

CREATE TABLE USERINFO (
  IDX                          NUMBER(11,0) NOT NULL,
  COMPANY_IDX                  NUMBER,
  BIO_TYPE                     NUMBER,
  SERVICENAME                  VARCHAR2(512) NOT NULL,
  USERID                       VARCHAR2(512) NOT NULL,
  AAID                         VARCHAR2(128) NOT NULL,
  AUTHENTICATORVERSION         NUMBER DEFAULT 0 NOT NULL,
  KEYID                        VARCHAR2(1024),
  PUBKEY                       VARCHAR2(2048),
  CERTIFICATE                  VARCHAR2(2048),
  SIGNCOUNTER                  NUMBER DEFAULT 0 NOT NULL,
  UVS                          VARCHAR2(64),
  STATUS                       VARCHAR2(20) DEFAULT 'O' NOT NULL,
  REGTIME                      TIMESTAMP DEFAULT sysdate NOT NULL,
  CREATEDTIME                  TIMESTAMP DEFAULT sysdate NOT NULL,
  CONSTRAINT USERINFO_PK PRIMARY KEY (IDX)
);

CREATE TABLE CHALLENGE (
  IDX                          NUMBER(11,0) NOT NULL,
  COMPANY_IDX                  NUMBER(11,0),
  USERID                       VARCHAR2(512),
  SERVICENAME                  VARCHAR2(512),
  CHALLENGECODE                VARCHAR2(140),
  CREATETIME                   TIMESTAMP DEFAULT sysdate NOT NULL,
  LOGIDX                       NUMBER(11,0) DEFAULT -1 NOT NULL,
  UV                           VARCHAR2(20),
  CONSTRAINT CHALLENGE_PK PRIMARY KEY (IDX)
);

CREATE TABLE CRITERIA (
  IDX                          NUMBER(11,0) NOT NULL,
  AAID                         VARCHAR2(64),
  VENDORIDS                    VARCHAR2(32),
  USERVERIFICATION             NUMBER,
  KEYPROTECTION                NUMBER,
  MATCHERPROTECTION            NUMBER,
  ATTACHMENTHNUMBER            NUMBER,
  TCDISPLAY                    NUMBER,
  TCDISPLAYCONTENTTYPE         VARCHAR2(128) DEFAULT 'text/plain',
  AUTHENTICATIONALGORITHMS     VARCHAR2(64),
  ASSERTIONSCHEMES             VARCHAR2(64) DEFAULT 'UAFV1TLV',
  ATTESTATIONTYPES             VARCHAR2(64),
  AUTHENTICATORVERSION         NUMBER,
  METAHASH                     VARCHAR2(512),
  JSONDATA                     CLOB DEFAULT EMPTY_CLOB(),
  CREATETIME                   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATEDTIME                  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT CRITERIA_PK PRIMARY KEY (IDX)
);

CREATE TABLE SIGN (
  IDX                          NUMBER(11,0) NOT NULL,
  COMPANY_IDX                  NUMBER,
  USERID                       VARCHAR2(512) NOT NULL,
  ASSERTION                    VARCHAR2(4000) NOT NULL,
  DN                           VARCHAR2(200),
  PLAINTEXT                    CLOB DEFAULT EMPTY_CLOB(),
  DATA                         VARCHAR2(2000) NOT NULL,
  SIGNATURE                    VARCHAR2(1000) NOT NULL,
  MEMO                         VARCHAR2(64),
  DEL                          VARCHAR2(1) DEFAULT 'N',
  CREATETIME                   TIMESTAMP DEFAULT sysdate NOT NULL,
  CONSTRAINT SIGN_PK PRIMARY KEY (IDX)
);

CREATE TABLE TRANSACTIONHASH (
  IDX                          NUMBER(11,0) NOT NULL,
  COMPANY_IDX                  NUMBER,
  USERID                       VARCHAR2(512),
  CONTENT                      CLOB DEFAULT EMPTY_CLOB(),
  CONTENTHASH                  VARCHAR2(64),
  CREATETIME                   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT TRANSACTIONHASH_PK PRIMARY KEY (IDX)
);

CREATE TABLE TRANSACTION_CONFIRMATION (
  IDX                          NUMBER(11,0) NOT NULL,
  COMPANY_IDX                  NUMBER,
  USERID                       VARCHAR2(512),
  AAID                         VARCHAR2(64),
  CONTENTTYPE                  VARCHAR2(128),
  CONTENT                      CLOB DEFAULT EMPTY_CLOB(),
  CREATEDTIME                  TIMESTAMP DEFAULT sysdate,
  CONSTRAINT TRANSACTION_CONFIRMATION_PK PRIMARY KEY (IDX)
);

CREATE TABLE FIDO2_METADATA (
  IDX                          NUMBER(11,0) NOT NULL,
  DESCRIPTION                  VARCHAR2(256),
  AAGUID                       VARCHAR2(256),
  ALTERNATIVEDESCRIPTIONS      VARCHAR2(2048),
  PROTOCOLFAMILY               VARCHAR2(128),
  AUTHENTICATORVERSION         NUMBER(38,0),
  UPV                          VARCHAR2(512),
  ASSERTIONSCHME               VARCHAR2(128),
  AUTHENTICATIONALGORITHM      NUMBER(38,0),
  PUBLICKEYALGANDENCODING      NUMBER(38,0),
  ATTESTATIONTYPES             VARCHAR2(2048),
  USERVERIFICATIONDETAILS      VARCHAR2(2048),
  KEYPROTECTION                NUMBER(38,0),
  MATCHERPROTECTION            NUMBER(38,0),
  CRYPTOSTRENGTH               NUMBER(38,0),
  OPERATINGENV                 VARCHAR2(2048),
  ATTACHMENTHINT               NUMBER(38,0),
  ISSECONDFACTORONLY           VARCHAR2(8),
  TCDISPLAY                    NUMBER(38,0),
  ATTESTATIONROOTCERTIFICATES  CLOB DEFAULT EMPTY_CLOB(),
  ICON                         CLOB DEFAULT EMPTY_CLOB(),
  SKI                          VARCHAR2(2048),
  CREATEDTIME                  TIMESTAMP DEFAULT sysdate,
  CONSTRAINT FIDO2_METADATA_PK PRIMARY KEY (IDX)
);

CREATE TABLE FIDO2_CREDENTIAL_PARAMS (
  IDX                          NUMBER(11,0) NOT NULL,
  CRED_TYPE                    VARCHAR2(32) DEFAULT 'public-key' NOT NULL,
  CRED_ALG                     NUMBER(38,0),
  STATUS                       VARCHAR2(1) DEFAULT 'T' NOT NULL,
  CREATEDTIME                  TIMESTAMP DEFAULT sysdate,
  CONSTRAINT FIDO2_CREDENTIAL_PARAMS_PK PRIMARY KEY (IDX)
);

CREATE TABLE FIDO2_DEMO_ACCESS_CODE (
  ACCESSCODE                   VARCHAR2(128) NOT NULL,
  VENDORNAME                   VARCHAR2(128),
  STARTTIME                    NUMBER,
  ENDTIME                      NUMBER,
  STATUS                       VARCHAR2(1) DEFAULT 'E' NOT NULL,
  NOTE                         VARCHAR2(300),
  ETC                          VARCHAR2(1024)
);

CREATE TABLE FIDO_LOGS (
  IDX                          NUMBER(11,0) NOT NULL,
  COMPANY_IDX                  NUMBER NOT NULL,
  SERIALCODE                   VARCHAR2(128) NOT NULL,
  SERVICENAME                  VARCHAR2(512) NOT NULL,
  JSONDATA                     CLOB DEFAULT EMPTY_CLOB(),
  CREATEDTIME                  TIMESTAMP DEFAULT sysdate,
  CONSTRAINT FIDO_LOGS_PK PRIMARY KEY (IDX)
);

CREATE TABLE FIDO_LOGS_20210101 (
  IDX                          NUMBER(11,0) NOT NULL,
  COMPANY_IDX                  NUMBER NOT NULL,
  SERIALCODE                   VARCHAR2(128) NOT NULL,
  SERVICENAME                  VARCHAR2(512) NOT NULL,
  JSONDATA                     CLOB DEFAULT EMPTY_CLOB(),
  CREATEDTIME                  TIMESTAMP DEFAULT sysdate,
  CONSTRAINT FIDO_LOGS_20210101_PK PRIMARY KEY (IDX)
);

CREATE TABLE FIDO_LOGS_20210102 (
  IDX                          NUMBER(11,0) NOT NULL,
  COMPANY_IDX                  NUMBER NOT NULL,
  SERIALCODE                   VARCHAR2(128) NOT NULL,
  SERVICENAME                  VARCHAR2(512) NOT NULL,
  JSONDATA                     CLOB DEFAULT EMPTY_CLOB(),
  CREATEDTIME                  TIMESTAMP DEFAULT sysdate,
  CONSTRAINT FIDO_LOGS_20210102_PK PRIMARY KEY (IDX)
);

CREATE TABLE BAK_FIDO_LOGS_BAK (
  IDX                          NUMBER(11,0) NOT NULL,
  COMPANY_IDX                  NUMBER NOT NULL,
  SERIALCODE                   VARCHAR2(128) NOT NULL,
  SERVICENAME                  VARCHAR2(512) NOT NULL,
  JSONDATA                     CLOB DEFAULT EMPTY_CLOB(),
  CREATEDTIME                  TIMESTAMP,
  DEC_JSONDATA                 CLOB,
  CONSTRAINT BAK_FIDO_LOGS_BAK_PK PRIMARY KEY (IDX)
);

CREATE TABLE BAK_FIDO_LOGS_TEST (
  IDX                          NUMBER(11,0) NOT NULL,
  COMPANY_IDX                  NUMBER NOT NULL,
  SERIALCODE                   VARCHAR2(128) NOT NULL,
  SERVICENAME                  VARCHAR2(512) NOT NULL,
  JSONDATA                     CLOB DEFAULT EMPTY_CLOB(),
  CREATEDTIME                  TIMESTAMP,
  CONSTRAINT BAK_FIDO_LOGS_TEST_PK PRIMARY KEY (IDX)
);

CREATE TABLE FIDO_STATISTICS (
  COMPANY_IDX                  NUMBER DEFAULT 0 NOT NULL,
  SERVICE_NAME                 VARCHAR2(512) NOT NULL,
  GROUPBY                      VARCHAR2(32) NOT NULL,
  CREATEDTIME                  TIMESTAMP DEFAULT sysdate NOT NULL,
  AUTH_S                       NUMBER DEFAULT 0,
  AUTH_F                       NUMBER DEFAULT 0,
  TC_S                         NUMBER DEFAULT 0,
  TC_F                         NUMBER DEFAULT 0,
  REG_S                        NUMBER DEFAULT 0,
  REG_F                        NUMBER DEFAULT 0,
  DEREG_S                      NUMBER DEFAULT 0,
  DEREG_F                      NUMBER DEFAULT 0
);

CREATE TABLE FIDO_STATISTICS_BAK (
  COMPANY_IDX                  NUMBER DEFAULT 0 NOT NULL,
  SERVICE_NAME                 VARCHAR2(512) NOT NULL,
  GROUPBY                      VARCHAR2(32) NOT NULL,
  CREATEDTIME                  TIMESTAMP DEFAULT sysdate NOT NULL,
  AUTH_S                       NUMBER DEFAULT 0,
  AUTH_F                       NUMBER DEFAULT 0,
  TC_S                         NUMBER DEFAULT 0,
  TC_F                         NUMBER DEFAULT 0,
  REG_S                        NUMBER DEFAULT 0,
  REG_F                        NUMBER DEFAULT 0,
  DEREG_S                      NUMBER DEFAULT 0,
  DEREG_F                      NUMBER DEFAULT 0
);

CREATE TABLE CCFA_AUDIT_LOG (
  IDX                          NUMBER NOT NULL,
  COMPANY_IDX                  NUMBER NOT NULL,
  COMPANY_NAME                 VARCHAR2(512) NOT NULL,
  TYPE                         VARCHAR2(32) NOT NULL,
  USER_ID                      VARCHAR2(64) NOT NULL,
  USER_NAME                    VARCHAR2(32) NOT NULL,
  MESSAGE                      VARCHAR2(4000) NOT NULL,
  IP                           VARCHAR2(15),
  UA                           VARCHAR2(2048),
  INTERGRITY_HASH              VARCHAR2(512),
  CREATEDTIME                  TIMESTAMP DEFAULT sysdate NOT NULL,
  CONSTRAINT CCFA_AUDIT_LOG_PK PRIMARY KEY (IDX)
);

CREATE TABLE CCFA_COMPANY (
  IDX                          NUMBER NOT NULL,
  COMPANY_NAME                 VARCHAR2(256),
  COMPANY_TYPE                 VARCHAR2(20),
  VENDOR_CODE                  VARCHAR2(20),
  CONTACT                      VARCHAR2(512),
  CONTACT_PHONE                VARCHAR2(50),
  CONTACT_PHONE2               VARCHAR2(50),
  CONTACT_ADDR                 VARCHAR2(2048),
  ENABLE_TYPE                  VARCHAR2(20),
  STARTTIME                    TIMESTAMP DEFAULT sysdate,
  ENDTIME                      TIMESTAMP DEFAULT TO_TIMESTAMP('9999-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS'),
  MAX_APPID                    NUMBER DEFAULT 0 NOT NULL,
  MAX_APPSERVER                NUMBER DEFAULT 0 NOT NULL,
  MAX_USER                     NUMBER DEFAULT 0 NOT NULL,
  ETC                          VARCHAR2(4000),
  CREATOR                      NUMBER,
  UPDATOR                      NUMBER,
  CREATEDTIME                  TIMESTAMP DEFAULT sysdate NOT NULL,
  UPDATEDTIME                  TIMESTAMP DEFAULT sysdate NOT NULL,
  CONSTRAINT CCFA_COMPANY_PK PRIMARY KEY (IDX)
);

CREATE TABLE CCFA_CRITERIA (
  IDX                          NUMBER(11,0) NOT NULL,
  AAID                         VARCHAR2(64),
  METAHASH                     VARCHAR2(512),
  JSONDATA                     CLOB DEFAULT EMPTY_CLOB(),
  CREATETIME                   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATEDTIME                  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT CCFA_CRITERIA_PK PRIMARY KEY (IDX)
);

CREATE TABLE CCFA_ERROR_TABLE (
  ERROR_CODE                   VARCHAR2(20) NOT NULL,
  ERROR_MESSAGE                VARCHAR2(1024),
  ERROR_COMMENT                VARCHAR2(4000),
  ERROR_TYPE                   VARCHAR2(20)
);

CREATE TABLE CCFA_EXCEPTIONS (
  IDX                          NUMBER NOT NULL,
  COMPANY_IDX                  NUMBER DEFAULT 0,
  E_TYPE                       VARCHAR2(32),
  E_LEVEL                      VARCHAR2(32),
  EXCEPTION_MESSAGE            VARCHAR2(4000),
  EXCEPTION_DETAIL_MESSAGE     VARCHAR2(4000),
  EXCEPTION_DATA               CLOB DEFAULT EMPTY_CLOB(),
  CREATEDTIME                  VARCHAR2(64),
  CONSTRAINT CCFA_EXCEPTIONS_PK PRIMARY KEY (IDX)
);

CREATE TABLE CCFA_FDS_POLICY (
  COMPANY_IDX                  NUMBER NOT NULL,
  AND_IP                       VARCHAR2(4000),
  AND_TERM                     VARCHAR2(32),
  AND_DEVICE                   VARCHAR2(16),
  AND_COUNTRY                  VARCHAR2(16) NOT NULL,
  OR_IP                        VARCHAR2(4000),
  OR_TERM                      VARCHAR2(32),
  OR_COUNTRY                   VARCHAR2(16) NOT NULL,
  CREATEDTIME                  TIMESTAMP DEFAULT sysdate NOT NULL,
  UPDATEDTIME                  TIMESTAMP DEFAULT sysdate NOT NULL,
  CONSTRAINT CCFA_FDS_POLICY_PK PRIMARY KEY (COMPANY_IDX)
);

CREATE TABLE CCFA_FIDOCLIENT (
  SERVERCODE                   VARCHAR2(64) NOT NULL,
  SERVERNAME                   VARCHAR2(1024) NOT NULL,
  SERVERURL                    VARCHAR2(2048) NOT NULL,
  STATUS                       VARCHAR2(4) DEFAULT 'ON' NOT NULL,
  CREATEDTIME                  TIMESTAMP DEFAULT sysdate NOT NULL,
  UPDATEDTIME                  TIMESTAMP DEFAULT sysdate NOT NULL
);

CREATE TABLE CCFA_FIELDS (
  IDX                          NUMBER NOT NULL,
  FIELD_TABLE                  VARCHAR2(128) NOT NULL,
  FIELD_NAME                   VARCHAR2(256) NOT NULL,
  FIELD_TYPE                   VARCHAR2(128) NOT NULL,
  FIELD_TITLE                  VARCHAR2(128),
  PK                           NUMBER DEFAULT 0 NOT NULL,
  FK                           NUMBER DEFAULT 0 NOT NULL,
  OPTION_IDX                   NUMBER,
  EDITABLE                     NUMBER(38,0) DEFAULT 0 NOT NULL,
  CONSTRAINT CCFA_FIELDS_PK PRIMARY KEY (IDX)
);

CREATE TABLE CCFA_LICENSE (
  IDX                          NUMBER NOT NULL,
  COMPANY_IDX                  NUMBER,
  COMPANY_NAME                 VARCHAR2(256),
  CONTACT_NAME                 VARCHAR2(128),
  CONTACT_PHONE                VARCHAR2(128),
  CONTACT_EMAIL                VARCHAR2(256),
  SERVICE_NAME                 VARCHAR2(256),
  ETC                          VARCHAR2(1024),
  LICENSE                      VARCHAR2(2048),
  FILE_PATH                    VARCHAR2(256),
  HASHVALUE                    VARCHAR2(256),
  CREATEDTIME                  TIMESTAMP DEFAULT sysdate NOT NULL,
  UPDATEDTIME                  TIMESTAMP DEFAULT sysdate NOT NULL,
  CONSTRAINT CCFA_LICENSE_PK PRIMARY KEY (IDX)
);

CREATE TABLE CCFA_MAILING (
  IDX                          NUMBER NOT NULL,
  COMPANY_IDX                  NUMBER DEFAULT 0,
  "TO"                         VARCHAR2(4000),
  SUBJECT                      VARCHAR2(256),
  CONTENT                      VARCHAR2(4000),
  STATUS                       VARCHAR2(256),
  SMS_TO                       VARCHAR2(4000),
  SMS_CONTENT                  VARCHAR2(300),
  SMS_STATUS                   VARCHAR2(512),
  SENDTIME                     VARCHAR2(64),
  CONSTRAINT CCFA_MAILING_PK PRIMARY KEY (IDX)
);

CREATE TABLE CCFA_MANAGER (
  IDX                          NUMBER NOT NULL,
  USER_ID                      VARCHAR2(64) NOT NULL,
  USER_PW                      VARCHAR2(128) NOT NULL,
  USER_NM                      VARCHAR2(50),
  USER_EMAIL                   VARCHAR2(256),
  USER_PHONE                   VARCHAR2(20),
  COMPANY_IDX                  NUMBER DEFAULT 0 NOT NULL,
  STATUS                       VARCHAR2(20),
  LOGIN                        VARCHAR2(20) DEFAULT 'OFF-LINE',
  BLOCK_TIME                   TIMESTAMP,
  LAST_ACCESS                  TIMESTAMP,
  ETC                          VARCHAR2(2048),
  ALRAM_TYPE                   VARCHAR2(32) DEFAULT 'none' NOT NULL,
  ALRAM_LEVEL                  VARCHAR2(20) DEFAULT '0' NOT NULL,
  CREATEDTIME                  TIMESTAMP DEFAULT sysdate NOT NULL,
  UPDATEDTIME                  TIMESTAMP DEFAULT sysdate NOT NULL,
  CONSTRAINT CCFA_MANAGER_PK PRIMARY KEY (IDX)
);

CREATE TABLE CCFA_MANAGER_PW_POLICY (
  IDX                          NUMBER NOT NULL,
  USER_ID                      VARCHAR2(64) NOT NULL,
  ACCOUNT_LOCK                 VARCHAR2(1) DEFAULT 'N',
  PW_FAIL_CNT                  NUMBER DEFAULT 1,
  CREATEDTIME                  TIMESTAMP DEFAULT sysdate NOT NULL,
  UPDATEDTIME                  TIMESTAMP DEFAULT sysdate NOT NULL,
  CONSTRAINT CCFA_MANAGER_PW_POLICY_PK PRIMARY KEY (IDX)
);

CREATE TABLE CCFA_MENU (
  IDX                          NUMBER(11,0) NOT NULL,
  MENU_NAME                    VARCHAR2(32),
  MENU_CODE                    VARCHAR2(32),
  MENU_PARENT_IDX              NUMBER DEFAULT 0 NOT NULL,
  MENU_ICON                    VARCHAR2(64),
  MENU_URL                     VARCHAR2(512),
  MENU_SEQ                     NUMBER,
  TBL_NAME                     VARCHAR2(128),
  PK                           VARCHAR2(128),
  VISIBLE                      VARCHAR2(20) DEFAULT 'true' NOT NULL,
  OPEN_TYPE                    VARCHAR2(20) DEFAULT 'open',
  STATISTICS                   VARCHAR2(20) DEFAULT 'N',
  READONLY                     VARCHAR2(20) DEFAULT 'N' NOT NULL,
  CONSTRAINT CCFA_MENU_PK PRIMARY KEY (IDX)
);

CREATE TABLE CCFA_OPTION (
  IDX                          NUMBER NOT NULL,
  OPTION_NAME                  VARCHAR2(64),
  OPTION_NOTE                  VARCHAR2(64),
  OPTION_TITLE                 VARCHAR2(64),
  CONSTRAINT CCFA_OPTION_PK PRIMARY KEY (IDX)
);

CREATE TABLE CCFA_OPTIONS (
  IDX                          NUMBER NOT NULL,
  OPTION_IDX                   NUMBER,
  OPTION_VALUE                 VARCHAR2(128),
  OPTION_TITLE                 VARCHAR2(128),
  OPTION_NOTE                  VARCHAR2(128),
  CONSTRAINT CCFA_OPTIONS_PK PRIMARY KEY (IDX)
);

CREATE TABLE CCFA_STATISTICS (
  IDX                          NUMBER NOT NULL,
  OWNER_IDX                    NUMBER,
  TYPE                         VARCHAR2(16),
  OPEN_TYPE                    VARCHAR2(20) DEFAULT 'close' NOT NULL,
  GROUP1_IDX                   NUMBER,
  GROUP2_IDX                   NUMBER,
  TARGET_IDX                   NUMBER,
  GRAPH_TYPE                   VARCHAR2(32),
  TITLE                        VARCHAR2(1024),
  CONTENT                      VARCHAR2(4000),
  PRIME_FIELD_IDX              NUMBER,
  "LIMIT"                      NUMBER,
  REALTIME                     VARCHAR2(20) DEFAULT 'custom' NOT NULL,
  ETC                          VARCHAR2(4000),
  CREATEDTIME                  TIMESTAMP DEFAULT sysdate NOT NULL,
  UPDATEDTIME                  TIMESTAMP DEFAULT sysdate NOT NULL,
  CONSTRAINT CCFA_STATISTICS_PK PRIMARY KEY (IDX)
);

CREATE TABLE CCFA_STATISTICS_FILTER (
  STATISTICS_IDX               NUMBER NOT NULL,
  COLUMN_NAME                  VARCHAR2(256) NOT NULL,
  OP                           VARCHAR2(20) NOT NULL,
  "VALUE"                      VARCHAR2(1024) NOT NULL,
  TYPE                         VARCHAR2(20) DEFAULT 'F'
);

CREATE TABLE CCFA_STATISTICS_ORDER (
  STATISTICS_IDX               NUMBER NOT NULL,
  COLUMN_NAME                  VARCHAR2(128) NOT NULL,
  TYPE                         VARCHAR2(20) NOT NULL
);

CREATE TABLE CCFA_SYSTEM_INFO (
  PROP_KEY                     VARCHAR2(128) NOT NULL,
  PROP_VALUE                   VARCHAR2(1024),
  UPDATEDTIME                  TIMESTAMP DEFAULT sysdate,
  CONSTRAINT CCFA_SYSTEM_INFO_PK PRIMARY KEY (PROP_KEY)
);

CREATE TABLE CCFA_SYSTEM_PROP (
  PROP_KEY                     VARCHAR2(128) NOT NULL,
  COMPANY_IDX                  NUMBER DEFAULT 0 NOT NULL,
  PROP_VALUE                   VARCHAR2(4000),
  SHARE_TYPE                   VARCHAR2(20) DEFAULT 'NO',
  UPDATEDTIME                  TIMESTAMP DEFAULT sysdate
);

CREATE TABLE AWS_INFO (
  IDX                          NUMBER NOT NULL,
  COMPANY_IDX                  NUMBER(38,0) NOT NULL,
  AMZ_TOKEN                    VARCHAR2(512),
  CUSTOMER_ID                  VARCHAR2(512),
  PRODUCT_CODE                 VARCHAR2(512),
  CUSTOMER_AWS_ACCOUNT_ID      VARCHAR2(512),
  DIMENSION                    VARCHAR2(100),
  EXPIRATIONDATE               VARCHAR2(100),
  CREATEDTIME                  TIMESTAMP DEFAULT sysdate NOT NULL,
  UPDATEDTIME                  TIMESTAMP DEFAULT sysdate NOT NULL,
  CONSTRAINT AWS_INFO_PK PRIMARY KEY (IDX)
);

-- ---------- 고유 제약 / 보조 인덱스 (ERD 인덱스 목록) ----------
ALTER TABLE CCFA_MANAGER ADD CONSTRAINT CCFA_MANAGER_USER_ID_UK UNIQUE (USER_ID);
CREATE INDEX CRITERIA_AAID ON CRITERIA (AAID);
CREATE INDEX CCFA_CRITERIA_AAID ON CCFA_CRITERIA (AAID);
CREATE INDEX FIDO2_CREDENTIAL_PARAMS_ALG ON FIDO2_CREDENTIAL_PARAMS (CRED_ALG);

-- ---------- 시퀀스 + IDX 컬럼 기본값 (IDX 보유 29개 테이블) ----------
-- 시드 데이터가 1~999 를 쓰므로 1000 부터 시작한다.
CREATE SEQUENCE APPID_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE APPID MODIFY IDX DEFAULT APPID_SEQ.NEXTVAL;
CREATE SEQUENCE APPSERVER_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE APPSERVER MODIFY IDX DEFAULT APPSERVER_SEQ.NEXTVAL;
CREATE SEQUENCE USERINFO_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE USERINFO MODIFY IDX DEFAULT USERINFO_SEQ.NEXTVAL;
CREATE SEQUENCE CHALLENGE_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE CHALLENGE MODIFY IDX DEFAULT CHALLENGE_SEQ.NEXTVAL;
CREATE SEQUENCE CRITERIA_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE CRITERIA MODIFY IDX DEFAULT CRITERIA_SEQ.NEXTVAL;
CREATE SEQUENCE SIGN_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE SIGN MODIFY IDX DEFAULT SIGN_SEQ.NEXTVAL;
CREATE SEQUENCE TRANSACTIONHASH_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE TRANSACTIONHASH MODIFY IDX DEFAULT TRANSACTIONHASH_SEQ.NEXTVAL;
CREATE SEQUENCE TRANSACTION_CONFIRMATION_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE TRANSACTION_CONFIRMATION MODIFY IDX DEFAULT TRANSACTION_CONFIRMATION_SEQ.NEXTVAL;
CREATE SEQUENCE FIDO2_METADATA_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE FIDO2_METADATA MODIFY IDX DEFAULT FIDO2_METADATA_SEQ.NEXTVAL;
CREATE SEQUENCE FIDO2_CREDENTIAL_PARAMS_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE FIDO2_CREDENTIAL_PARAMS MODIFY IDX DEFAULT FIDO2_CREDENTIAL_PARAMS_SEQ.NEXTVAL;
CREATE SEQUENCE FIDO_LOGS_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE FIDO_LOGS MODIFY IDX DEFAULT FIDO_LOGS_SEQ.NEXTVAL;
CREATE SEQUENCE FIDO_LOGS_20210101_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE FIDO_LOGS_20210101 MODIFY IDX DEFAULT FIDO_LOGS_20210101_SEQ.NEXTVAL;
CREATE SEQUENCE FIDO_LOGS_20210102_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE FIDO_LOGS_20210102 MODIFY IDX DEFAULT FIDO_LOGS_20210102_SEQ.NEXTVAL;
CREATE SEQUENCE BAK_FIDO_LOGS_BAK_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE BAK_FIDO_LOGS_BAK MODIFY IDX DEFAULT BAK_FIDO_LOGS_BAK_SEQ.NEXTVAL;
CREATE SEQUENCE BAK_FIDO_LOGS_TEST_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE BAK_FIDO_LOGS_TEST MODIFY IDX DEFAULT BAK_FIDO_LOGS_TEST_SEQ.NEXTVAL;
CREATE SEQUENCE CCFA_AUDIT_LOG_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE CCFA_AUDIT_LOG MODIFY IDX DEFAULT CCFA_AUDIT_LOG_SEQ.NEXTVAL;
CREATE SEQUENCE CCFA_COMPANY_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE CCFA_COMPANY MODIFY IDX DEFAULT CCFA_COMPANY_SEQ.NEXTVAL;
CREATE SEQUENCE CCFA_CRITERIA_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE CCFA_CRITERIA MODIFY IDX DEFAULT CCFA_CRITERIA_SEQ.NEXTVAL;
CREATE SEQUENCE CCFA_EXCEPTIONS_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE CCFA_EXCEPTIONS MODIFY IDX DEFAULT CCFA_EXCEPTIONS_SEQ.NEXTVAL;
CREATE SEQUENCE CCFA_FIELDS_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE CCFA_FIELDS MODIFY IDX DEFAULT CCFA_FIELDS_SEQ.NEXTVAL;
CREATE SEQUENCE CCFA_LICENSE_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE CCFA_LICENSE MODIFY IDX DEFAULT CCFA_LICENSE_SEQ.NEXTVAL;
CREATE SEQUENCE CCFA_MAILING_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE CCFA_MAILING MODIFY IDX DEFAULT CCFA_MAILING_SEQ.NEXTVAL;
CREATE SEQUENCE CCFA_MANAGER_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE CCFA_MANAGER MODIFY IDX DEFAULT CCFA_MANAGER_SEQ.NEXTVAL;
CREATE SEQUENCE CCFA_MANAGER_PW_POLICY_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE CCFA_MANAGER_PW_POLICY MODIFY IDX DEFAULT CCFA_MANAGER_PW_POLICY_SEQ.NEXTVAL;
CREATE SEQUENCE CCFA_MENU_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE CCFA_MENU MODIFY IDX DEFAULT CCFA_MENU_SEQ.NEXTVAL;
CREATE SEQUENCE CCFA_OPTION_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE CCFA_OPTION MODIFY IDX DEFAULT CCFA_OPTION_SEQ.NEXTVAL;
CREATE SEQUENCE CCFA_OPTIONS_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE CCFA_OPTIONS MODIFY IDX DEFAULT CCFA_OPTIONS_SEQ.NEXTVAL;
CREATE SEQUENCE CCFA_STATISTICS_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE CCFA_STATISTICS MODIFY IDX DEFAULT CCFA_STATISTICS_SEQ.NEXTVAL;
CREATE SEQUENCE AWS_INFO_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE;
ALTER TABLE AWS_INFO MODIFY IDX DEFAULT AWS_INFO_SEQ.NEXTVAL;

COMMIT;
