-- ============================================================
-- 로컬 검증 전용 시드 데이터. 운영 DB에 절대 적용하지 말 것.
-- 계정: superuser / Admin1234!  (COMPANY_IDX 0, SUPER)
--       kbadmin   / Company1234! (COMPANY_IDX 1, COMPANY)
-- ============================================================
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = KBFIDO;

-- 고객사: IDX 0 은 전역(superuser) 레코드. 없으면 로그인 조인이 깨진다.
INSERT INTO CCFA_COMPANY (IDX, COMPANY_NAME, COMPANY_TYPE, VENDOR_CODE, CONTACT, ENABLE_TYPE, MAX_APPID, MAX_APPSERVER, MAX_USER)
VALUES (0, '전역(시스템)', 'SYSTEM', 'CC', 'admin@crosscert.local', 'Y', 0, 0, 0);
INSERT INTO CCFA_COMPANY (IDX, COMPANY_NAME, COMPANY_TYPE, VENDOR_CODE, CONTACT, CONTACT_PHONE, ENABLE_TYPE, MAX_APPID, MAX_APPSERVER, MAX_USER)
VALUES (1, 'KB국민은행', 'BANK', 'KB', 'fido@kb.local', '02-0000-0000', 'Y', 10, 10, 100000);
INSERT INTO CCFA_COMPANY (IDX, COMPANY_NAME, COMPANY_TYPE, VENDOR_CODE, CONTACT, ENABLE_TYPE, MAX_APPID, MAX_APPSERVER, MAX_USER)
VALUES (2, '테스트고객사', 'TEST', 'TS', 'test@test.local', 'N', 1, 1, 100);

-- 운영자 (USER_PW = SHA-256 hex)
INSERT INTO CCFA_MANAGER (IDX, USER_ID, USER_PW, USER_NM, USER_EMAIL, COMPANY_IDX, STATUS)
VALUES (1, 'superuser', '5ce41ada64f1e8ffb0acfaafa622b141438f3a5777785e7f0b830fb73e40d3d6', '슈퍼관리자', 'super@crosscert.local', 0, '활성');
INSERT INTO CCFA_MANAGER (IDX, USER_ID, USER_PW, USER_NM, USER_EMAIL, COMPANY_IDX, STATUS)
VALUES (2, 'kbadmin', 'c9d4b06722e867564a14b87c43c62c620f10023d4adeabcea4728d915196c461', 'KB운영자', 'kbadmin@kb.local', 1, '활성');
INSERT INTO CCFA_MANAGER (IDX, USER_ID, USER_PW, USER_NM, COMPANY_IDX, STATUS)
VALUES (3, 'disabled', 'c9d4b06722e867564a14b87c43c62c620f10023d4adeabcea4728d915196c461', '비활성운영자', 1, '비활성');
INSERT INTO CCFA_MANAGER_PW_POLICY (IDX, USER_ID, ACCOUNT_LOCK, PW_FAIL_CNT) VALUES (1, 'superuser', 'N', 0);
INSERT INTO CCFA_MANAGER_PW_POLICY (IDX, USER_ID, ACCOUNT_LOCK, PW_FAIL_CNT) VALUES (2, 'kbadmin', 'N', 0);

-- 시스템 설정
INSERT INTO CCFA_SYSTEM_PROP (PROP_KEY, COMPANY_IDX, PROP_VALUE, SHARE_TYPE) VALUES ('PW_FAIL_LIMIT', 0, '5', 'YES');
INSERT INTO CCFA_SYSTEM_PROP (PROP_KEY, COMPANY_IDX, PROP_VALUE, SHARE_TYPE) VALUES ('SESSION_TIMEOUT', 0, '30', 'NO');
INSERT INTO CCFA_SYSTEM_PROP (PROP_KEY, COMPANY_IDX, PROP_VALUE, SHARE_TYPE) VALUES ('SERVICE_NAME', 1, 'kbstar', 'NO');
INSERT INTO CCFA_SYSTEM_INFO (PROP_KEY, PROP_VALUE) VALUES ('VERSION', '1.0.0');
INSERT INTO CCFA_SYSTEM_INFO (PROP_KEY, PROP_VALUE) VALUES ('BUILD_DATE', '2026-09-16');
INSERT INTO CCFA_ERROR_TABLE (ERROR_CODE, ERROR_MESSAGE, ERROR_COMMENT, ERROR_TYPE) VALUES ('1200', 'OK', '정상 처리', 'INFO');
INSERT INTO CCFA_ERROR_TABLE (ERROR_CODE, ERROR_MESSAGE, ERROR_COMMENT, ERROR_TYPE) VALUES ('1498', 'INVALID_SIGNATURE', '서명 검증 실패', 'ERROR');
INSERT INTO CCFA_FIDOCLIENT (SERVERCODE, SERVERNAME, SERVERURL, STATUS) VALUES ('FIDO01', 'FIDO 서버 1', 'https://fido1.internal:8443', 'ON');
INSERT INTO CCFA_FIDOCLIENT (SERVERCODE, SERVERNAME, SERVERURL, STATUS) VALUES ('FIDO02', 'FIDO 서버 2', 'https://fido2.internal:8443', 'OFF');

-- FIDO 인증 도메인
INSERT INTO APPID (IDX, COMPANY_IDX, APPID, MEMO, STATUS, DEVICE, DEVICE_DEFAULT, SERVICENAME)
VALUES (1, 1, 'https://kbstar.com/facets.json', 'KB 스타뱅킹', 'use', 'android', 'T', 'kbstar');
INSERT INTO APPID (IDX, COMPANY_IDX, APPID, MEMO, STATUS, DEVICE, DEVICE_DEFAULT, SERVICENAME)
VALUES (2, 1, 'ios:bundle-id:com.kbstar.kbbank', 'KB 스타뱅킹 iOS', 'use', 'ios', 'F', 'kbstar');
INSERT INTO APPID (IDX, COMPANY_IDX, APPID, MEMO, STATUS, DEVICE, DEVICE_DEFAULT, SERVICENAME)
VALUES (3, 2, 'https://test.local/facets.json', '테스트', 'unuse', 'android', 'F', 'testsvc');
INSERT INTO APPSERVER (IDX, COMPANY_IDX, MEMBER_CODE, MEMBER_ID, TYPE, NOTE) VALUES (1, 1, 'KB001', 'kbserver01', 'use', '운영 서버');
INSERT INTO APPSERVER (IDX, COMPANY_IDX, MEMBER_CODE, MEMBER_ID, TYPE, NOTE) VALUES (2, 2, 'TS001', 'tsserver01', 'use', '테스트');
INSERT INTO USERINFO (IDX, COMPANY_IDX, BIO_TYPE, SERVICENAME, USERID, AAID, AUTHENTICATORVERSION, KEYID, PUBKEY, CERTIFICATE, SIGNCOUNTER, UVS, STATUS)
VALUES (1, 1, 1, 'kbstar', 'user001', '0012#0001', 1, 'keyid-001', 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE-PUBKEY-SAMPLE-001', 'MIIB-CERT-SAMPLE-001', 12, '2', 'O');
INSERT INTO USERINFO (IDX, COMPANY_IDX, BIO_TYPE, SERVICENAME, USERID, AAID, AUTHENTICATORVERSION, KEYID, PUBKEY, CERTIFICATE, SIGNCOUNTER, UVS, STATUS)
VALUES (2, 1, 2, 'kbstar', 'user002', '0012#0002', 1, 'keyid-002', 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE-PUBKEY-SAMPLE-002', 'MIIB-CERT-SAMPLE-002', 3, '16', 'O');
INSERT INTO USERINFO (IDX, COMPANY_IDX, BIO_TYPE, SERVICENAME, USERID, AAID, AUTHENTICATORVERSION, KEYID, PUBKEY, CERTIFICATE, SIGNCOUNTER, UVS, STATUS)
VALUES (3, 2, 1, 'testsvc', 'tester', '0012#0001', 1, 'keyid-003', 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE-PUBKEY-SAMPLE-003', 'MIIB-CERT-SAMPLE-003', 0, '2', 'X');
INSERT INTO CHALLENGE (IDX, COMPANY_IDX, USERID, SERVICENAME, CHALLENGECODE, LOGIDX, UV) VALUES (1, 1, 'user001', 'kbstar', 'chal-0001', -1, 'fingerprint');
INSERT INTO CHALLENGE (IDX, COMPANY_IDX, USERID, SERVICENAME, CHALLENGECODE, LOGIDX, UV) VALUES (2, 1, 'user002', 'kbstar', 'chal-0002', 1, 'face');
INSERT INTO CRITERIA (IDX, AAID, VENDORIDS, USERVERIFICATION, KEYPROTECTION, MATCHERPROTECTION, ATTACHMENTHNUMBER, TCDISPLAY, AUTHENTICATIONALGORITHMS, ATTESTATIONTYPES, AUTHENTICATORVERSION, METAHASH, JSONDATA)
VALUES (1, '0012#0001', '0012', 2, 2, 2, 1, 1, '1', '15879', 1, 'hash-0001', '{"aaid":"0012#0001","description":"Sample fingerprint"}');
INSERT INTO CRITERIA (IDX, AAID, VENDORIDS, USERVERIFICATION, KEYPROTECTION, MATCHERPROTECTION, ATTACHMENTHNUMBER, TCDISPLAY, AUTHENTICATIONALGORITHMS, ATTESTATIONTYPES, AUTHENTICATORVERSION, METAHASH, JSONDATA)
VALUES (2, '0012#0002', '0012', 16, 2, 2, 1, 1, '1', '15879', 1, 'hash-0002', '{"aaid":"0012#0002","description":"Sample face"}');
INSERT INTO CCFA_CRITERIA (IDX, AAID, METAHASH, JSONDATA) VALUES (1, '0012#0001', 'hash-0001', '{"aaid":"0012#0001","policy":"admin"}');
INSERT INTO SIGN (IDX, COMPANY_IDX, USERID, ASSERTION, DN, PLAINTEXT, DATA, SIGNATURE, MEMO, DEL)
VALUES (1, 1, 'user001', 'assertion-sample-001', 'CN=user001', '이체 100,000원 승인', 'data-001', 'sig-001', '이체', 'N');
INSERT INTO TRANSACTIONHASH (IDX, COMPANY_IDX, USERID, CONTENT, CONTENTHASH) VALUES (1, 1, 'user001', '이체 100,000원', 'a1b2c3');
INSERT INTO TRANSACTION_CONFIRMATION (IDX, COMPANY_IDX, USERID, AAID, CONTENTTYPE, CONTENT) VALUES (1, 1, 'user001', '0012#0001', 'text/plain', '거래확인 내용');

-- FIDO2
INSERT INTO FIDO2_METADATA (IDX, DESCRIPTION, AAGUID, PROTOCOLFAMILY, AUTHENTICATORVERSION, UPV, ASSERTIONSCHME, AUTHENTICATIONALGORITHM, PUBLICKEYALGANDENCODING, ATTESTATIONTYPES, KEYPROTECTION, MATCHERPROTECTION, CRYPTOSTRENGTH, ATTACHMENTHINT, ISSECONDFACTORONLY, TCDISPLAY, ATTESTATIONROOTCERTIFICATES, ICON, SKI)
VALUES (1, 'YubiKey 5 Series', 'cb69481e-8ff7-4039-93ec-0a2729a154a8', 'fido2', 50100, '[{"major":1,"minor":0}]', 'FIDOV2', 1, 260, 'basic_full', 10, 4, 128, 2, 'false', 0, 'MIIC-ROOT-CERT-SAMPLE', 'data:image/png;base64,iVBORw0KGgo=', 'ski-0001');
INSERT INTO FIDO2_METADATA (IDX, DESCRIPTION, AAGUID, PROTOCOLFAMILY, AUTHENTICATORVERSION, ASSERTIONSCHME, AUTHENTICATIONALGORITHM, PUBLICKEYALGANDENCODING, ATTESTATIONTYPES, ISSECONDFACTORONLY)
VALUES (2, 'Samsung Pass', '53414d53-554e-4700-0000-000000000000', 'fido2', 1, 'FIDOV2', 1, 260, 'basic_full', 'false');
INSERT INTO FIDO2_CREDENTIAL_PARAMS (IDX, CRED_TYPE, CRED_ALG, STATUS) VALUES (1, 'public-key', -7, 'T');
INSERT INTO FIDO2_CREDENTIAL_PARAMS (IDX, CRED_TYPE, CRED_ALG, STATUS) VALUES (2, 'public-key', -257, 'T');
INSERT INTO FIDO2_CREDENTIAL_PARAMS (IDX, CRED_TYPE, CRED_ALG, STATUS) VALUES (3, 'public-key', -8, 'F');
INSERT INTO FIDO2_DEMO_ACCESS_CODE (ACCESSCODE, VENDORNAME, STARTTIME, ENDTIME, STATUS, NOTE) VALUES ('DEMO-0001', '벤더A', 1767225600, 1798761600, 'E', '데모용');
INSERT INTO FIDO2_DEMO_ACCESS_CODE (ACCESSCODE, VENDORNAME, STARTTIME, ENDTIME, STATUS, NOTE) VALUES ('DEMO-0002', '벤더B', 1767225600, 1770000000, 'D', '만료');

-- 로그
INSERT INTO FIDO_LOGS (IDX, COMPANY_IDX, SERIALCODE, SERVICENAME, JSONDATA, CREATEDTIME)
VALUES (1, 1, 'SN-0001', 'kbstar', '{"op":"Auth","userid":"user001","result":"1200"}', SYSTIMESTAMP - INTERVAL '1' DAY);
INSERT INTO FIDO_LOGS (IDX, COMPANY_IDX, SERIALCODE, SERVICENAME, JSONDATA, CREATEDTIME)
VALUES (2, 1, 'SN-0002', 'kbstar', '{"op":"Reg","userid":"user002","result":"1200"}', SYSTIMESTAMP - INTERVAL '2' HOUR);
INSERT INTO FIDO_LOGS (IDX, COMPANY_IDX, SERIALCODE, SERVICENAME, JSONDATA, CREATEDTIME)
VALUES (3, 2, 'SN-0003', 'testsvc', '{"op":"Auth","userid":"tester","result":"1498"}', SYSTIMESTAMP);
INSERT INTO CCFA_AUDIT_LOG (IDX, COMPANY_IDX, COMPANY_NAME, TYPE, USER_ID, USER_NAME, MESSAGE, IP, UA, INTERGRITY_HASH)
VALUES (1, 0, '전역(시스템)', 'LOGIN', 'superuser', '슈퍼관리자', '로그인 성공', '127.0.0.1', 'seed', 'seed-hash-1');
INSERT INTO CCFA_AUDIT_LOG (IDX, COMPANY_IDX, COMPANY_NAME, TYPE, USER_ID, USER_NAME, MESSAGE, IP, UA, INTERGRITY_HASH)
VALUES (2, 1, 'KB국민은행', 'UPDATE', 'kbadmin', 'KB운영자', 'APPID UPDATE 1', '10.0.0.5', 'seed', 'seed-hash-2');
INSERT INTO CCFA_EXCEPTIONS (IDX, COMPANY_IDX, E_TYPE, E_LEVEL, EXCEPTION_MESSAGE, EXCEPTION_DETAIL_MESSAGE, EXCEPTION_DATA, CREATEDTIME)
VALUES (1, 1, 'AUTH', 'ERROR', 'Invalid signature', 'signature mismatch for user001', '{"trace":"..."}', '2026-09-15 10:00:00');
INSERT INTO CCFA_MAILING (IDX, COMPANY_IDX, "TO", SUBJECT, CONTENT, STATUS, SMS_TO, SMS_CONTENT, SMS_STATUS, SENDTIME)
VALUES (1, 1, 'ops@kb.local', '[FIDO] 장애 알림', '인증 실패율 증가', 'SENT', '010-0000-0000', '인증 실패율 증가', 'SENT', '2026-09-15 10:05:00');

-- 어드민 메타 (데이터로만 취급)
INSERT INTO CCFA_MENU (IDX, MENU_NAME, MENU_CODE, MENU_PARENT_IDX, MENU_ICON, MENU_URL, MENU_SEQ, TBL_NAME, PK, VISIBLE, OPEN_TYPE, STATISTICS, READONLY)
VALUES (1, 'FIDO', 'FIDO', 0, 'shield', NULL, 1, NULL, NULL, 'true', 'open', 'N', 'N');
INSERT INTO CCFA_MENU (IDX, MENU_NAME, MENU_CODE, MENU_PARENT_IDX, MENU_ICON, MENU_URL, MENU_SEQ, TBL_NAME, PK, VISIBLE, OPEN_TYPE, STATISTICS, READONLY)
VALUES (2, '앱 ID', 'APPID', 1, NULL, '/appids', 1, 'APPID', 'IDX', 'true', 'open', 'N', 'N');
INSERT INTO CCFA_OPTION (IDX, OPTION_NAME, OPTION_NOTE, OPTION_TITLE) VALUES (1, 'STATUS', '사용 상태', '상태');
INSERT INTO CCFA_OPTIONS (IDX, OPTION_IDX, OPTION_VALUE, OPTION_TITLE, OPTION_NOTE) VALUES (1, 1, 'use', '사용', NULL);
INSERT INTO CCFA_OPTIONS (IDX, OPTION_IDX, OPTION_VALUE, OPTION_TITLE, OPTION_NOTE) VALUES (2, 1, 'unuse', '미사용', NULL);
INSERT INTO CCFA_FIELDS (IDX, FIELD_TABLE, FIELD_NAME, FIELD_TYPE, FIELD_TITLE, PK, FK, OPTION_IDX, EDITABLE)
VALUES (1, 'APPID', 'STATUS', 'select', '상태', 0, 0, 1, 1);
INSERT INTO CCFA_LICENSE (IDX, COMPANY_IDX, COMPANY_NAME, CONTACT_NAME, CONTACT_PHONE, CONTACT_EMAIL, SERVICE_NAME, LICENSE, HASHVALUE)
VALUES (1, 1, 'KB국민은행', '홍길동', '02-0000-0000', 'fido@kb.local', 'kbstar', 'LICENSE-SAMPLE-KEY', 'hash');
INSERT INTO CCFA_FDS_POLICY (COMPANY_IDX, AND_IP, AND_TERM, AND_DEVICE, AND_COUNTRY, OR_IP, OR_TERM, OR_COUNTRY)
VALUES (1, '10.0.0.0/8', '30', 'mobile', 'KR', NULL, NULL, 'KR');
INSERT INTO CCFA_STATISTICS (IDX, OWNER_IDX, TYPE, OPEN_TYPE, GRAPH_TYPE, TITLE, "LIMIT", REALTIME)
VALUES (1, 1, 'bar', 'open', 'bar', '일별 인증', 30, 'custom');
INSERT INTO CCFA_STATISTICS_FILTER (STATISTICS_IDX, COLUMN_NAME, OP, "VALUE", TYPE) VALUES (1, 'SERVICE_NAME', '=', 'kbstar', 'F');
INSERT INTO CCFA_STATISTICS_ORDER (STATISTICS_IDX, COLUMN_NAME, TYPE) VALUES (1, 'CREATEDTIME', 'DESC');
INSERT INTO AWS_INFO (IDX, COMPANY_IDX, AMZ_TOKEN, CUSTOMER_ID, PRODUCT_CODE, CUSTOMER_AWS_ACCOUNT_ID, DIMENSION, EXPIRATIONDATE)
VALUES (1, 2, 'amz-token-sample', 'cust-0001', 'prod-0001', '123456789012', 'users', '2027-12-31');

-- 최근 30일 일별 통계 (GROUPBY = 'day')
BEGIN
  FOR i IN 0..29 LOOP
    INSERT INTO FIDO_STATISTICS (COMPANY_IDX, SERVICE_NAME, GROUPBY, CREATEDTIME, AUTH_S, AUTH_F, TC_S, TC_F, REG_S, REG_F, DEREG_S, DEREG_F)
    VALUES (1, 'kbstar', 'day', TRUNC(SYSDATE) - i, 1000 + MOD(i * 37, 400), MOD(i * 7, 40), 200 + MOD(i * 13, 90), MOD(i * 3, 10), 50 + MOD(i * 11, 60), MOD(i, 5), MOD(i * 5, 20), MOD(i, 3));
    INSERT INTO FIDO_STATISTICS (COMPANY_IDX, SERVICE_NAME, GROUPBY, CREATEDTIME, AUTH_S, AUTH_F, TC_S, TC_F, REG_S, REG_F, DEREG_S, DEREG_F)
    VALUES (2, 'testsvc', 'day', TRUNC(SYSDATE) - i, 10 + MOD(i, 9), MOD(i, 4), 0, 0, MOD(i, 3), 0, 0, 0);
  END LOOP;
END;
/
COMMIT;
